// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/property-mobile/CardStack.tsx": () => import("../components/mockups/property-mobile/CardStack.tsx"),
  "./components/mockups/property-mobile/EditorialFeed.tsx": () => import("../components/mockups/property-mobile/EditorialFeed.tsx"),
  "./components/mockups/property-mobile/ImmersiveHero.tsx": () => import("../components/mockups/property-mobile/ImmersiveHero.tsx")
};
